
import datetime
from django.utils import timezone

dummy_events = [
    {
        "title": "VIT-AP Hackathon 2025",
        "slug": "vit-ap-hackathon-2025",
        "description": "An intensive hackathon organized by VIT-AP University focusing on innovation and technology.",
        "event_type": "hackathon",
        "start_time": timezone.make_aware(datetime.datetime(2025, 3, 15, 9, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 3, 15, 21, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 3, 10, 23, 59)),
        "location": "VIT-AP Campus, Amaravati",
        "organizer": "VIT-AP University",
        "max_participants": 150,
    },
    {
        "title": "SRM AP Seminar on AI",
        "slug": "srm-ap-seminar-on-ai",
        "description": "A seminar discussing the latest advancements in Artificial Intelligence hosted by SRM AP.",
        "event_type": "seminar",
        "start_time": timezone.make_aware(datetime.datetime(2025, 4, 10, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 4, 10, 12, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 4, 5, 17, 0)),
        "location": "SRM Institute Campus, Andhra Pradesh",
        "organizer": "SRM Institute of Science and Technology, AP",
        "max_participants": 100,
    },
    {
        "title": "Siddhartha Workshop on Robotics",
        "slug": "siddhartha-workshop-on-robotics",
        "description": "Hands-on workshop focusing on robotics and automation, organized by Siddhartha Institute.",
        "event_type": "workshop",
        "start_time": timezone.make_aware(datetime.datetime(2025, 5, 5, 9, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 5, 5, 16, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 5, 1, 18, 0)),
        "location": "Siddhartha College, Andhra Pradesh",
        "organizer": "Siddhartha Institute of Engineering & Technology",
        "max_participants": 80,
    },
    {
        "title": "GITAM Conference on Emerging Technologies",
        "slug": "gitam-conference-on-emerging-technologies",
        "description": "A conference exploring emerging technologies in various fields hosted by GITAM University.",
        "event_type": "conference",
        "start_time": timezone.make_aware(datetime.datetime(2025, 6, 20, 8, 30)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 6, 20, 17, 30)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 6, 15, 23, 59)),
        "location": "GITAM University Campus, Andhra Pradesh",
        "organizer": "GITAM University",
        "max_participants": 200,
    },
    {
        "title": "Amrita Hackathon: Code for Good",
        "slug": "amrita-hackathon-code-for-good",
        "description": "A hackathon aimed at solving social challenges through innovative coding solutions.",
        "event_type": "hackathon",
        "start_time": timezone.make_aware(datetime.datetime(2025, 7, 10, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 7, 10, 22, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 7, 5, 23, 59)),
        "location": "Amrita University Campus, Andhra Pradesh",
        "organizer": "Amrita University",
        "max_participants": 120,
    },
    {
        "title": "VIT-AP Seminar: Cyber Security Trends",
        "slug": "vit-ap-seminar-cyber-security-trends",
        "description": "A seminar discussing the latest trends and challenges in cyber security.",
        "event_type": "seminar",
        "start_time": timezone.make_aware(datetime.datetime(2025, 8, 1, 14, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 8, 1, 16, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 7, 28, 18, 0)),
        "location": "VIT-AP University Auditorium, Amaravati",
        "organizer": "VIT-AP University",
        "max_participants": 100,
    },
    {
        "title": "SRM AP Workshop: IoT Innovations",
        "slug": "srm-ap-workshop-iot-innovations",
        "description": "A practical workshop on the latest IoT innovations and applications.",
        "event_type": "workshop",
        "start_time": timezone.make_aware(datetime.datetime(2025, 9, 12, 9, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 9, 12, 15, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 9, 7, 23, 59)),
        "location": "SRM Institute Lab, Andhra Pradesh",
        "organizer": "SRM Institute of Science and Technology, AP",
        "max_participants": 90,
    },
    {
        "title": "Siddhartha Conference: Future of Engineering",
        "slug": "siddhartha-conference-future-of-engineering",
        "description": "A conference discussing future trends and innovations in engineering.",
        "event_type": "conference",
        "start_time": timezone.make_aware(datetime.datetime(2025, 10, 5, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 10, 5, 18, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 10, 1, 20, 0)),
        "location": "Siddhartha College Auditorium, Andhra Pradesh",
        "organizer": "Siddhartha Institute of Engineering & Technology",
        "max_participants": 150,
    },
    {
        "title": "GITAM Hackathon: Smart Solutions",
        "slug": "gitam-hackathon-smart-solutions",
        "description": "A hackathon focusing on creating smart solutions for urban challenges.",
        "event_type": "hackathon",
        "start_time": timezone.make_aware(datetime.datetime(2025, 11, 11, 8, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 11, 11, 20, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 11, 6, 23, 59)),
        "location": "GITAM University Innovation Lab, Andhra Pradesh",
        "organizer": "GITAM University",
        "max_participants": 130,
    },
    {
        "title": "Amrita Seminar: Data Science Revolution",
        "slug": "amrita-seminar-data-science-revolution",
        "description": "A seminar exploring the impact of data science in modern industries.",
        "event_type": "seminar",
        "start_time": timezone.make_aware(datetime.datetime(2025, 12, 2, 11, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2025, 12, 2, 13, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2025, 11, 28, 23, 59)),
        "location": "Amrita University Conference Hall, Andhra Pradesh",
        "organizer": "Amrita University",
        "max_participants": 100,
    },
    {
        "title": "VIT-AP Workshop: Mobile App Development",
        "slug": "vit-ap-workshop-mobile-app-development",
        "description": "A workshop dedicated to mobile app development covering both Android and iOS platforms.",
        "event_type": "workshop",
        "start_time": timezone.make_aware(datetime.datetime(2026, 1, 15, 9, 30)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 1, 15, 17, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 1, 10, 23, 59)),
        "location": "VIT-AP University Tech Lab, Amaravati",
        "organizer": "VIT-AP University",
        "max_participants": 110,
    },
    {
        "title": "SRM AP Conference: Sustainable Technology",
        "slug": "srm-ap-conference-sustainable-technology",
        "description": "A conference discussing sustainable technology and green innovations.",
        "event_type": "conference",
        "start_time": timezone.make_aware(datetime.datetime(2026, 2, 20, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 2, 20, 18, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 2, 15, 23, 59)),
        "location": "SRM Institute Main Hall, Andhra Pradesh",
        "organizer": "SRM Institute of Science and Technology, AP",
        "max_participants": 180,
    },
    {
        "title": "Siddhartha Hackathon: Innovate to Elevate",
        "slug": "siddhartha-hackathon-innovate-to-elevate",
        "description": "A hackathon encouraging innovative solutions to modern engineering problems.",
        "event_type": "hackathon",
        "start_time": timezone.make_aware(datetime.datetime(2026, 3, 8, 9, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 3, 8, 21, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 3, 3, 23, 59)),
        "location": "Siddhartha College Innovation Center, Andhra Pradesh",
        "organizer": "Siddhartha Institute of Engineering & Technology",
        "max_participants": 140,
    },
    {
        "title": "GITAM Seminar: Blockchain Basics",
        "slug": "gitam-seminar-blockchain-basics",
        "description": "A seminar providing insights into blockchain technology and its applications.",
        "event_type": "seminar",
        "start_time": timezone.make_aware(datetime.datetime(2026, 4, 12, 13, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 4, 12, 15, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 4, 8, 23, 59)),
        "location": "GITAM University Seminar Hall, Andhra Pradesh",
        "organizer": "GITAM University",
        "max_participants": 100,
    },
    {
        "title": "Amrita Workshop: Machine Learning Bootcamp",
        "slug": "amrita-workshop-machine-learning-bootcamp",
        "description": "An intensive bootcamp covering various aspects of machine learning and AI.",
        "event_type": "workshop",
        "start_time": timezone.make_aware(datetime.datetime(2026, 5, 20, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 5, 20, 16, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 5, 15, 23, 59)),
        "location": "Amrita University Lab, Andhra Pradesh",
        "organizer": "Amrita University",
        "max_participants": 90,
    },
    {
        "title": "VIT-AP Conference: Digital Transformation",
        "slug": "vit-ap-conference-digital-transformation",
        "description": "A conference on the impact of digital transformation across industries.",
        "event_type": "conference",
        "start_time": timezone.make_aware(datetime.datetime(2026, 6, 25, 9, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 6, 25, 17, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 6, 20, 23, 59)),
        "location": "VIT-AP University Conference Room, Amaravati",
        "organizer": "VIT-AP University",
        "max_participants": 160,
    },
    {
        "title": "SRM AP Hackathon: Code Mania",
        "slug": "srm-ap-hackathon-code-mania",
        "description": "A fast-paced hackathon that challenges participants to solve real-world problems.",
        "event_type": "hackathon",
        "start_time": timezone.make_aware(datetime.datetime(2026, 7, 15, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 7, 15, 22, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 7, 10, 23, 59)),
        "location": "SRM Institute, Andhra Pradesh",
        "organizer": "SRM Institute of Science and Technology, AP",
        "max_participants": 150,
    },
    {
        "title": "Siddhartha Seminar: Renewable Energy Trends",
        "slug": "siddhartha-seminar-renewable-energy-trends",
        "description": "A seminar focusing on renewable energy sources and sustainable practices.",
        "event_type": "seminar",
        "start_time": timezone.make_aware(datetime.datetime(2026, 8, 5, 11, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 8, 5, 13, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 8, 1, 23, 59)),
        "location": "Siddhartha College, Andhra Pradesh",
        "organizer": "Siddhartha Institute of Engineering & Technology",
        "max_participants": 100,
    },
    {
        "title": "GITAM Workshop: Cloud Computing Essentials",
        "slug": "gitam-workshop-cloud-computing-essentials",
        "description": "A workshop aimed at providing a solid foundation in cloud computing technologies.",
        "event_type": "workshop",
        "start_time": timezone.make_aware(datetime.datetime(2026, 9, 10, 9, 30)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 9, 10, 15, 30)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 9, 5, 23, 59)),
        "location": "GITAM University Cloud Lab, Andhra Pradesh",
        "organizer": "GITAM University",
        "max_participants": 110,
    },
    {
        "title": "Amrita Conference: Tech Innovators Summit",
        "slug": "amrita-conference-tech-innovators-summit",
        "description": "A summit bringing together leading tech innovators and industry experts.",
        "event_type": "conference",
        "start_time": timezone.make_aware(datetime.datetime(2026, 10, 15, 10, 0)),
        "end_time": timezone.make_aware(datetime.datetime(2026, 10, 15, 18, 0)),
        "registration_deadline": timezone.make_aware(datetime.datetime(2026, 10, 10, 23, 59)),
        "location": "Amrita University Grand Hall, Andhra Pradesh",
        "organizer": "Amrita University",
        "max_participants": 200,
    },
]

# Example: Creating Event instances (if using Django shell or a script)
# from your_app.models import Event
# for event_data in dummy_events:
#     Event.objects.create(**event_data)
