# Generated by Django 5.1.4 on 2025-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the event.', max_length=200)),
                ('slug', models.SlugField(help_text='Unique URL-friendly identifier for the event.', unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed information about the event.')),
                ('event_type', models.CharField(choices=[('hackathon', 'Hackathon'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference')], default='seminar', help_text='Type of the event.', max_length=20)),
                ('start_time', models.DateTimeField(help_text='Date and time when the event starts.')),
                ('end_time', models.DateTimeField(help_text='Date and time when the event ends.')),
                ('registration_deadline', models.DateTimeField(blank=True, help_text='Deadline for event registration (if applicable).', null=True)),
                ('location', models.CharField(help_text='Event location or online meeting URL.', max_length=200)),
                ('organizer', models.CharField(help_text='Name of the organizer or organizing entity.', max_length=100)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants allowed.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
            },
        ),
    ]
